### PR TITLE
enh: updated mgwr and spvcm

### PR DESCRIPTION
**Pull request by sjsrey**
This incorporates the new releases of mgwr and svcm.

Note that:
```
nosetests pysal/model
```
will have 4 failures (at least locally) for spint. Which are known failures which we may skip decorate later.

### CODE REVIEW

**Comment by weikang9009** [comment]
spint also has [a new github release](https://github.com/pysal/spint/releases/tag/v1.0.5)

**Comment by sjsrey** [comment]
> Looks great! One thing that might need to be updated is the references in spreg docstrings [pysal/spreg#1](https://github.com/pysal/spreg/issues/1)

Agreed. I think the changes have to be made in spreg?

**Comment by weikang9009** [comment]
> Agreed. I think the changes have to be made in spreg?

Agreed. And I think spreg does not have a doc website ready at the moment?

**Comment by pedrovma** [comment]
Sorry, but to be honest, I have no clue about what should be done in spreg regarding this issue.

**Comment by ljwolf** [comment]
@sjsrey as I recall correctly, you fixed the bib stuff for spreg in ljwolf/spreg#1

**Comment by ljwolf** [comment]
@pedrovma [This](http://pysal.org/getting_started.html#building-an-online-documentation-for-the-submodule-mimicking-giddy-docs) is the directions. I had started this mid-November for spreg, but was sidetracked with travel. We need to go through and [swap all the citation keys](http://pysal.org/getting_started.html#bibliography-and-cross-reference) from an old style to a new style.

**Pull request merged**
