### PR TITLE
Esda shuffle speedup

### PR DESCRIPTION
**Pull request by andy-esch**
Ref https://github.com/pysal/pysal/pull/755

/cc @ljwolf

### CODE REVIEW

**Comment by sjsrey** [comment]
Revisit at Scipy2016

**Comment by ljwolf** [comment]
Okay, so after some inspection, I'm concerned that something's up. Namely, when we use this patch over more data than the unittest, the expected change in the `p_z_sim` tend to be negative, so this technique, on average, generates smaller values. I'm not sure why this is the case from the code, so we're going to check them against the p-values in R for the same datasets.  

Thanks for bearing with us... this has taken a long time to review because these stats are pretty core to users & they also receive a lot of academic attention. We want to merge this, but have to make sure the patch isn't somehow skewing the `p_z_sim` estimates in a predictable way.

**Comment by ljwolf** [comment]
As a note to a contributor/maintainer who will pick this up:
- check pvalues over common datasets in:
    - [ ] `R` using `spdep`
    - [ ] OpenGeoDa
- ensure `p_z_sim` or equivalent statistics are within reasonable statistical distance to other packages.

**Comment by andy-esch** [comment]
Not a priority?

**Comment by ljwolf** [comment]
We need to direct it to [pysal/esda](https://github.com/pysal/esda) as the `dev` branch has been deleted. This closed by default when I deleted the unused `dev` branch.

Sorry about that...

**Pull request closed without merging**
