### PR TITLE
Spreg2

### PR DESCRIPTION
**Pull request by pedrovma**
Updating spreg to bring into pysal new developments on SUR models and bug fixes.
This PR is a work in progress.

### CODE REVIEW

**Comment by ljwolf** [comment]
Hey! Thanks! can I move this over to [`pysal/spreg`](https://github.com/pysal/spreg)?

**Comment by pedrovma** [comment]
@ljwolf Please notice that apparently I was careful enough to make sure spreg2 followed all spanel developments. Hence it seems there is no need to merge commit 4f0ac5b whatsoever.

**Comment by ljwolf** [comment]
OK! I'll be able to take a deep dive starting this afternoon, so I can also move the changes to pysal/spreg it if that's easier.

**Comment by sjsrey** [comment]
@ljwolf can we close this here? I think this moved to spreg?

**Comment by sjsrey** [comment]
Moved to https://github.com/pysal/spreg/issues/19

**Pull request closed without merging**
