### PR TITLE
bump requirements

### PR DESCRIPTION
**Pull request by sjsrey**

### CODE REVIEW

**Comment by jGaboardi** [comment]
Is it too late to include a fresh release of `spreg`? Yesterday @pedrovma asked me to cut a new one. After some infrastructure updates in pysal/spreg#99 it will be ready to go.

**Comment by sjsrey** [comment]
> 

I think we should hold off as we want to stick with the policy of freeze july 1?

**Comment by jGaboardi** [comment]
> I think we should hold off as we want to stick with the policy of freeze july 1?

Ah! I got my months confused. I thought it was an August 1st freeze :face_in_clouds:

**Comment by pedrovma** [comment]
Thank you so much, @jGaboardi ! My bad.

**Pull request merged**
