### PR TITLE
Handling coincident points

### PR DESCRIPTION
**Pull request by Aniq55**
1. [ ] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
2. [ ] This pull request is directed to the `pysal/master` branch. **This is important, as any PRs submitted against any other branches will be delayed.**
3. [ ] This pull introduces new functionality covered by
   [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and
   [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [ ] You have [assigned a
   reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/)
5. [ ] The justification for this PR is: Handling Coincident Points #941 #579

### CODE REVIEW

**Comment by ljwolf** [comment]
Hi @Aniq55, thanks for the contribution! 

We'll get some folks to review the PR before the next release. 

On first brush, I do have a few questions:
1. I can't speak for the rest of @pysal/devs, but I (and I think @iamwfx) were concerned about this in spatial KNNs, so the classes defined in `Distance.py`. I see this patches the kernel weight component of non-binary `DistanceBand` weights, but I think a full fix would resolve this at the construction of the KNN set. 
2. I think this mainly applies when the kernel is being set within `DistanceBand`. Would it make more sense to add this parameter into the operation at [line909?](https://github.com/pysal/pysal/blob/ff20f394f827472824a640ad080ca2e48c046fd1/pysal/weights/Distance.py#L909)

**Comment by Aniq55** [comment]
@ljwolf I'll look into it. thanks (:

**Comment by kaushikCanada** [comment]
any update on this please?

**Comment by ljwolf** [comment]
Hi @kaushikCanada, thanks for the prompting. I've had my [attention elsewhere](https://github.com/pysal/esda//pull/115) but I've just found what I think is a fix for this stashed away. 

Do you have data where this occurs explicitly still?

**Comment by kaushikCanada** [comment]
Hi Levi,

Thanks so much for your reply. Actually, I am doing doing house prices for
a client. The data contains adv. number and coordinates + price for last 2
years which is around 300k points. some of them are repeat sales so it
produces coincidental points. now when i do the knn_from dataframe() it
gives me this error that it cannot remove something from list. Let me know
if I can say more details.

Cheers,
Roy

**Comment by kaushikCanada** [comment]
Does this new module fix the coincident points thing?

**Comment by sjsrey** [comment]
Should this be moved to [libpysal](https://github.com/pysal/libpysal)?

**Comment by kaushikCanada** [comment]
i am so eager to download this fixed library and crunch through my points
dataset,
Any release date for this fix?

Thanks,
Roy

**Comment by sjsrey** [comment]
Closing as this has been migrated: https://github.com/pysal/libpysal/issues/362

**Pull request closed without merging**
