### PR TITLE
Py3 Conversion Project

### PR DESCRIPTION
**Pull request by ljwolf**
Here's the pull containing code that, when run through `2to3`, yields pysal valid in python 3. To check this code, follow the [directions in the wiki](https://github.com/pysal/pysal/wiki/Converting-2-to-3-Notes#working-on-the-port)

With this in place, all that's needed for distribution are:

1. setting up travis to test python 3.4 automatically. 
2. writing `setup.py` to automatically convert to python 3.

I'm making this pull because I think it's a good idea to separate substantive changes to the code (i.e. the large lifting in caching work in `spreg` (like [26c824](https://github.com/pysal/pysal/commit/26c824fe13dde00eec47cf7b7425090d56b88a2b)) from fiddling with travis and packaging.

Plus, I'm getting nervous about how long this branch has been detached from master :smile:

### CODE REVIEW

**Comment by ljwolf** [comment]
tests now pass on travis in both 2.7 and 3.4
pretty neat!

**Comment by dfolch** [comment]
The idea is that this 2 to 3 stuff is a one off transition. Once this code
is merged, substantive development of new methods would continue in the
SVN. The infrastructure to test spreg against both Python 2 and 3 would
need to be ported to the SVN, but this should not be too hard since it's
working on the github side. One of the trickiest issues in spreg had to do
with the cached attributes. Levi and Serge figured out a minimally invasive
way of doing the getting and setting that works in both 2 and 3.

-David

**Comment by sjsrey** [comment]
Let's hold off on merging until after the dev meeting on 8/14 so everyone has a chance to discuss this and understand what is involved.

**Comment by ljwolf** [comment]
uh oh, looks like my `git pull --rebase upstream master` duplicated all of the commits. 

Either we should reopen this or use a new PR from serge's branch :(

**Comment by ljwolf** [comment]
Closing, registering with the [wiki](https://github.com/pysal/pysal/wiki/Release-Candidates), and let serge merge [his clean rebase](https://github.com/sjsrey/pysal/tree/py3merge)

**Pull request closed without merging**
