### PR TITLE
update changelog for 23.07

### PR DESCRIPTION
**Pull request by sjsrey**

### CODE REVIEW

**Review by knaaptime — COMMENTED** [review]
😎

**Comment by jGaboardi** [comment]
Looks like I forgot to get an `spopt` release out in time... :grimacing:

**Comment by knaaptime** [comment]
if you cut one now, everyone still gets the latest and greatest if they `mamba install pysal` :)

**Comment by jGaboardi** [comment]
Haste makes waste. Next time I will make a note to do it before the deadline.

**Pull request merged**
