### PR TITLE
Add users to Travis

### PR DESCRIPTION
**Pull request by ljwolf**
adding myself to upstream travis notifications.

### CODE REVIEW

**Comment by ljwolf** [comment]
Feel free to hop on this if you'd like to get notifications about pull request status

**Comment by sjsrey** [comment]
I think the conflict is with  https://github.com/pysal/pysal/commit/c06e0160107a0e09295817239915b993c86f0390 but I can't get this to show up clearly on the command line.

We could close this, and do another one to get around this - basically phil.stphns@gmail.com got removed in the commit before this pr, while the pr added ljwolf

At least that is my sense of the conflict?

**Comment by ljwolf** [comment]
I think you're right. super weird on the conflict though. I'll close and reup.

**Comment by ljwolf** [comment]
added in a #640

**Pull request closed without merging**
