### PR TITLE
[REBASED] PySAL+ optional testing matrix

### PR DESCRIPTION
**Pull request by ljwolf**
This sets up a multi-environment test matrix for PySAL using an environment variable, `PYSAL_PLUS` & is the remaining blocker for #829 

If `PYSAL_PLUS`, we include pandas, numba, numexpr, shapely, and patsy in the testing environment. This way, if we have numba versions of computational functions, tabular methods, etc, these get tested. 

In theory, these should also be added to the `setup.py` `extras_require` flag, if we want to appropriately incorporate this metadata by module. 

It makes sense to make the `PYSAL_PLUS` environment as open as possible, as long as things were correctly wrapped in try/except or `common.requires`. <s> I will write that up in a wiki page, too. </s> I've written [this notebook](http://nbviewer.jupyter.org/gist/ljwolf/b9817ce4590994f20a77f783a9bff3f4) documenting things I've seen & tried.

### CODE REVIEW

**Comment by ljwolf** [comment]
adding tentative label in case anyone wants to call out extra packages to add to `PYSAL_PLUS`.

**Comment by ljwolf** [comment]
Just realized, visualization packages might be good to add here. At minimum, matplotlib & seaborn.

**Comment by Makosak** [comment]
Matplotlib templates in the new version includes a seaborn styling... Have
to look at that further, but could help

**Comment by ljwolf** [comment]
Rebased into #833.

**Pull request closed without merging**
