### PR TITLE
B726

### PR DESCRIPTION
**Pull request by sjsrey**
Some fine tuning in spreg/tests that will have to go back upstream to spreg, but travis passes now with unpinned scipy and numpy to development can move forward.

### CODE REVIEW

**Comment by ljwolf** [comment]
:tada: :balloon: :tada: will merge when passing. 

We should still look into using CircleCI for the private repositories. I can get circleCI running on my private spreg fork, but cannot test out how to set it up for `pysal/spreg`, since I'm not an admin.

**Comment by pedrovma** [comment]
Brilliant!

**Comment by sjsrey** [comment]
For future reference, when we are testing allclose and one of the parameters in the array is close to (or equal to) 0, just using rtol will lead to problems, since rtol*v will be 0. In that case using atol will be the way to go.

**Comment by pedrovma** [comment]
:+1:

**Pull request merged**
