### PR TITLE
Fixed code in ipython notebooks

### PR DESCRIPTION
**Pull request by pdoongarwal**
Fixed the code in ipython notebooks of viz module.

### CODE REVIEW

**Comment by pdoongarwal** [comment]
@sjsrey Ok
I have send the PR for dev branch only though.

I have also converted the current viz module to object-oriented, though I am still finalizing and testing it.
Should I report an Issue before sending a PR for that?

**Comment by sjsrey** [comment]
@pdoongarwal yes, add an issue so we can see what you have in mind.

**Comment by pdoongarwal** [comment]
@sjsrey Should I add anything else to this PR before you merge it?

**Comment by sjsrey** [comment]
I'm seeing errors in the folium_mapping.ipynb file when I run it. These need to be fixed before a PR gets merged.

**Comment by pdoongarwal** [comment]
Sorry for the mistake, I will have a look at it.
I am closing this PR, after I have made some important changes to viz module I will modify the ipython notebooks accordingly. Then I will send a PR.

**Comment by sjsrey** [comment]
When you run the your notebooks locally do you see the error reported in #762 ?
I still see that error in this pull request. Please note that the travis tests do not test notebooks - you have to test them locally.

**Comment by pdoongarwal** [comment]
Yes, I am also seeing that error.

**Comment by ljwolf** [comment]
Yes, the error is due to an update in Folium (I think) that removes `_build_map()` methods from folium map objects. @pdoongarwal, if you can figure out what the equivalet command is to dump a Folium map object to its source HTML/JS, then that method should replace `_build_map()` and fix the folium errors.

**Comment by ljwolf** [comment]
I've [submitted a fix](https://github.com/pdoongarwal/pysal/pull/1) to the folium code up to @pdoongarwal. Once that merges, the notebook should be fixed.

**Comment by TichyProgs** [comment]
so how do I now replace _build_map?

**Pull request closed without merging**
