### PR TITLE
Added String_Type values to unsupported file types

### PR DESCRIPTION
**Pull request by hasecbinusr**
This is my first PR, so please let me know if I'm doing it wrong.

1. [x] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
2. [x] This pull request is directed to the `pysal/dev` branch.
3. [ ] This pull introduces new functionality covered by
   [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and
   [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [ ] You have [assigned a
   reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/)
5. [x] The justification for this PR is: Added String_Type values to file type classes to resolve NotImplemented error not firing.

### CODE REVIEW

**Comment by hasecbinusr** [comment]
Fixes #932

**Comment by ljwolf** [comment]
Hey, before merging this, can you upload your polyline M (or a subset of it) so I can verify that this works on your use case?

**Comment by hasecbinusr** [comment]
[ArcM.zip](https://github.com/pysal/pysal/files/923108/ArcM.zip)

**Comment by ljwolf** [comment]
sweet:
```python
>>> import pysal as ps
>>> ps.open('./arcm_with_m.shp')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-5cec027328ef> in <module>()
----> 1 ps.open('arcm_with_m.shp')

/home/ljw/Downloads/pysal/core/IOHandlers/pyShpIO.py in __init__(self, *args, **kwargs)
     66         self.dataObj = None
     67         if self.mode == 'r' or self.mode == 'rb':
---> 68             self.__open()
     69         elif self.mode == 'w' or self.mode == 'wb':
     70             self.__create()

/home/ljw/Downloads/pysal/core/IOHandlers/pyShpIO.py in __open(self)
     84         except KeyError:
     85             raise TypeError('%s does not support shapes of type: %s'
---> 86                             % (self.__class__.__name__, self.dataObj.type()))
     87 
     88     def __create(self):

TypeError: PurePyShpWrapper does not support shapes of type: ARCM
```

that's what we want to see.

**Pull request merged**
