### PR TITLE
Network

### PR DESCRIPTION
**Pull request by jlaura**
Replacement for the existing WED implementation to support planar and non-planar networks.

Features:
Network Extraction
Digitized and Graph based representations
Contiguity based adjacency (W)
	Access to PySAL ESDA functionality which requires a W (LISAs)

Point Snapping
Network constrained distance computations
	Pairwise within a single pattern
  	Pairwise between a source and a destination pattern
Counts per Edge (Digitized or Graph)
F, G, and K Functions

### CODE REVIEW

**Comment by jlaura** [comment]
Todo
====

Should (Must) Have
---------------------------
Documentation
Edge segmentation
Tests

Nice to have
-------------------
Distance Band and Continuous W Generation

**Comment by dfolch** [comment]
Jay, can you make a style change. Line 37 in network.py has the parameter "in_shp". In the rest of pysal (that I checked) uses "shapefile".

**Comment by jlaura** [comment]
In the future the flow should probably have been: 

fetch upstream master and branch -> merge upstream master into upstream branch -> PR -> edit local branch in fork -> PR into upstream branch

This was modify branch -> merge master (fixing conflicts) -> PR into upstream branch

The former should have all of the merge items in one commit and all of the new code / modifications in another commit.  Right now, these are mixed...

**Comment by jlaura** [comment]
Going to close.  Going to merge in using the 1st method, above.

**Pull request closed without merging**
