### PR TITLE
speedup distance computations

### PR DESCRIPTION
**Pull request by dfolch**
This PR addresses #621.

By turning off ```generatetree()``` the time to compute a distance matrix is cut by approximately 90% (ymmv).  After turning this off, the code was tested using ```Network Usage.ipynb```.  The notebook tests most of the network module including NetworkG, NetworkK and Moran, and ran without problems.

### CODE REVIEW

**Comment by jlaura** [comment]
(1) Tests are failing at line 103 because the tree is being used there.  It appears that the tree is not used in the code (only the test).  We should confirm that the test coverage is what we want even when the tree is not generated (I think it is).

(2) This PR needs to rebase from master after merging the snapping code.

**Comment by dfolch** [comment]
1. Thanks for catching that test failure.  
 2. Is it enough to do a ```git pull upstream master``` into my local branch, or is something more sophisticated needed?

**Comment by jlaura** [comment]
Git fetch upstream master
Git checkout master
Git merge upstream/master

**Comment by dfolch** [comment]
I will reopen this under a new PR since my branch is a total mess.

**Pull request closed without merging**
