### PR TITLE
add action for building docs

### PR DESCRIPTION
**Pull request by sjsrey**

### CODE REVIEW

**Comment by jGaboardi** [comment]
@sjsrey This seems to be built from an older version of `main` -- it's running [`/.github/workflows/unittests.yml`](https://github.com/pysal/pysal/blob/ff2c05519ecfcb822b5c9ad68c1284f6fad9b9f0/.github/workflows/unittests.yml) and attempting build from Python 3.7 and 3.8, which are no longer in `main`.

The current CI workflow file is [`testing.yml`](https://github.com/pysal/pysal/blob/main/.github/workflows/testing.yml) which tests against [Python 3.{10,11,12}](https://github.com/pysal/pysal/tree/main/ci).

**Review by jGaboardi — APPROVED** [review]

**Comment by sjsrey** [comment]
This is [failing](https://github.com/pysal/pysal/actions/runs/9736345377/job/26866844330#step:5:11) when manually triggered. 

I'm not sure why 'sphinx-build' is not being installed?

**Comment by sjsrey** [comment]
This is [failing](https://github.com/pysal/pysal/actions/runs/9736345377/job/26866844330#step:5:11) when manually triggered. 

I'm not sure why 'sphinx-build' is not being installed?

**Comment by knaaptime** [comment]
i think we just need sphinx in [this file](https://github.com/pysal/pysal/blob/main/ci/312-latest.yaml)

actually, probably all of

```
- nbsphinx
- numpydoc
- sphinx
- sphinxcontrib-bibtex
- sphinx_bootstrap_theme
```

**Pull request merged**
