### PR TITLE
Networkrb

### PR DESCRIPTION
**Pull request by sjsrey**
This cherry picks from #624.

However, while the unit tests pass, the doctests in https://github.com/pysal/pysal/blob/master/pysal/network/network.py will fail and need to be fixed. They evidently were not tested before the merge?

See https://github.com/pysal/pysal/blob/master/pysal/network/network.py#L253
`counts` isn't defined in the scope of that doctest. there are other failures as well.

We shouldn't merge this until

- we agree that we have the right commits here from #624 
- the doctests are fixed

### CODE REVIEW

**Comment by dfolch** [comment]
Thanks for cherry picking... these are the only two commits I had intended for #624.

**Comment by jlaura** [comment]
Working on doctests now.

**Comment by jlaura** [comment]
Doc tests are fixed.  I pulled this PR locally to make the changes using:

git checkout -b sjsrey-networkrb master

git pull https://github.com/sjsrey/pysal.git networkrb

Any thoughts on how to update this PR from my side?

**Comment by dfolch** [comment]
@jlaura If it will make life easier, we can reject this PR (and #624).  You can put the network doctest fixes into its own PR (or add them to #628), and then I'll resubmit the topology stuff under a new PR after pulling those fixes.

**Comment by jlaura** [comment]
As a note - until the open PR for doc-tests is merged, it is going to be necessary to pull this PR locally and manually run the doctests to verify.

**Comment by sjsrey** [comment]
@jlaura we could keep the doctests separate for now, rather than have multiple prs hanging around waiting for another one to get closed. So once you and @dfolch are ok with the network related commits in this pr, this could be merged. Then we can revisit what to do about doctests in the upstream/travis testing. One option for the latter would be to have devs run doctests locally before a pr (as well as the unit tests) but leave the doctests off in travis.

**Comment by dfolch** [comment]
I think it would be safest to turn the doctests back on in travis (once everything is fixed).  I talked to @pedrovma and he is good with changes to spreg needed to get all the tests to pass. I'll submit a PR now to fix spreg.

@jlaura let me know if you have any questions about the topology stuff.  Here is a zoom-in on major roads in Rhode Island.  "Before" (without rounding and removing duplicate segments) and "after". The red dots are what pysal identifies as intersections, the blue lines are actual roads and the grey lines are graph edges.
none_false

11_true

**Pull request merged**
